name: "Pull Request"

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  pull_request:
    name: "Lint and Test"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.2"

      - name: "Set up Python"
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: "Install requirements"
        run: python3 -m pip install -r requirements.txt

      - name: "Lint"
        run: python3 -m ruff check

      - name: "Test"
        run: python3 -m unittest discover -v
        env: # Or as an environment variable
          HELLO: "WORLD"
