name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.2"

      # - name: "Adjust version number"
      #   shell: "bash"
      #   run: |
      #     yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
      #       "${{ github.workspace }}/custom_components/blaulichtsms/manifest.json"

      - name: "ZIP the source"
        shell: "bash"
        run: |
          zip hello.zip -r hello

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: ${{ github.workspace }}/hello.zip
